### ISSUE TITLE
CredentialsProviderError: Could not load credentials from any providers

### ISSUE THREAD

**Issue by Alexsandrogms** [ErickWendel/testing-serverless-apps#1]
Ao clonar o projeto e tentar executar conforme o vídeo postado no YouTube, me deparei com o seguinte erro: CredentialsProviderError: Could not load credentials from any providers. Com isso, adicionei o seguinte código no arquivo factory, e funcionou normalmente.

Codigo:
```
if (isLocal) {
	const host = process.env.LOCALSTACK_HOST || "localhost";
	s3config.endpoint = `http://${host}:4566`;
+	s3config.credentials = {
+		accessKeyId: "test",
+		secretAccessKey: "test",
+	};
}
```

**Comment by erick-medeiros** [comment]
Tem que colocar nas variáveis de ambiente do docker compose também

```yml
services:
  localstack:
    container_name: "localstack"
    image: localstack/localstack:3.2
    ports:
      - "4566:4566"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
```
